require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.4.0
  NewCops: enable

RSpec/ExampleLength:
 Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false
